name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk python3-pip zip unzip libssl-dev libffi-dev
          pip install buildozer==1.5.0 cython==0.29.33 kivy==2.2.0
      - name: Build
        run: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TrustLens-V8-APK
          path: bin/*.apk
